cookbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", auth_views.LoginView.as_view()),
    path("", include("recipes.urls")),
    path("", include("posts.urls")),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts" 
urlpatterns = [
    path("posts/", views.list, name="list"),
    path("posts/<int:id>/", views.details, name="details"),
    path("posts/add/", views.add, name="add"),
  
]

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path("recipes/", views.list, name="list"),
    path("recipes/<int:id>", views.details, name="details")
]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(
        verbose_name="tytuł",
        max_length=255)
    content = models.TextField()
    published = models.BooleanField()
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    
    

recipes/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    
    def __str__(self):
        return f"({self.id}) {self.title}"

posts/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post


# adres -> funkcja -> szablon
# posts -> list -> posts/list.html

def list(request):
    return render(
        request,
        "posts/list.html",
        {"posts": Post.objects.filter(published=True)}
    )

# posts/<int:id> -> details -> posts/details.html
def details(request, id):
    
    return render(
        request,
        "posts/details.html",
        {"post": Post.objects.get(id=id)}
    )

# GET posts/add -> create -> posts/add.html tu trzeba utworzyc formularz <form method="POST">
# POST posts/add -> create -> operacj dodania a nastepnie redirect

@login_required
def add(request):
    # if not request.user.is_authenticated:
    #     return HttpResponse("Zaloguj sie by dodac post")
    
    
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        author = request.user
        
        Post.objects.create(title=title, content=content, author=author, published=True)
        
        return redirect("posts:list")
    
    return render(
        request, 
        "posts/add.html"
    )
    
    

recipes/views.py
from django.shortcuts import render, redirect

from .models import Recipe

# Create your views here.

def list(request):
    return render(
        request, 
        "recipes/list.html",
        {"recipes": Recipe.objects.all()}
    )
    
    
def details(request, id):
    """
    /recipes/1 -> /recipes
    """
    return redirect("/recipes/")

posts/templates/posts/add.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Dodaj post</h1>
        <form method="POST">
            {% csrf_token %}
            <label for="title">Tytuł:</label><br>
            <input type="text" id="title" name="title"><br>
            <textarea id="w3review" name="content" rows="4" cols="50">
                Wpisz tresc
            </textarea><br>
            <input type="submit" value="dodaj">
        </form>
    </body>
</html>

posts/templates/posts/details.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>{{ post.title }}</h1>
        <div>{{ post.content }}</div>

        <footer><a href="{% url 'posts:list' %}">lista</a></footer>
    </body>
</html>

posts/templates/posts/list.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Lista postów</h1>
        <ul>
            {% for post in posts %}
            <li><a href="{% url 'posts:details' post.id  %}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

recipes/templates/recipes/list.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Lista receptur</h1>
        <ul>
            {% for recipe in recipes %}
            <li>{{ recipe.title }}</li>
            {% endfor %}
        </ul>
    </body>
</html>